name: Ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runtime:
          - win-x64
          - osx-x64
        include:
          - runtime: osx-x64
            os: macOS-latest

          - runtime: win-x64
            os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      
      - name: Build Windows
        if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
        run: go build -o app.exe
      
      - name: Build Mac
        if: startsWith(matrix.os, 'macos') && startsWith(matrix.runtime, 'osx-x64')
        run: go build -o app
      
      - name: Upload Mac x64 .dmg Artifact
        uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'macos') && startsWith(matrix.runtime, 'osx-x64')
        with:
          name: app
          path: app
          compression-level: 9
      
      - name: Upload Windows x64 .exe Artifact
        uses: actions/upload-artifact@v4
        if: startsWith(matrix.os, 'windows') && startsWith(matrix.runtime, 'win-x64')
        with:
          name: app
          path: app.exe
          compression-level: 9